from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path

from gb_monitor.account_sheet import (
    build_profile_deliverable,
    build_profile_signal_deliverable,
    build_profile_status,
    build_profile_usage_guide,
    build_profile_execution_board,
    build_client_verification_message,
    import_account_sheet,
    next_verification_target,
    update_verification_status,
)
from gb_monitor.config import Settings
from gb_monitor.feishu import FeishuNotifier, build_manual_report
from gb_monitor.logging import configure_logging
from gb_monitor.service import MonitorService, build_default_collectors
from gb_monitor.signal_rules import (
    build_signal_dashboard,
    build_signal_report,
    load_signal_candidates,
    load_signal_rules,
    match_candidates,
    matches_to_json,
    review_candidates,
)
from gb_monitor.signal_pipeline import run_profile_signal_pipeline
from gb_monitor.store_registry import (
    enabled_store_ids_by_platform,
    enabled_platform_binding_counts,
    load_registry,
    summarize_registry,
)
from gb_monitor.storage import Storage


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="gbm", description="Group buying monitor")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("init-db", help="Initialize sqlite schema")

    run = sub.add_parser("run", help="Run data collection")
    run.add_argument("--mode", choices=["scheduled", "all"], default="scheduled")
    run.add_argument("--dry-run", action="store_true")
    run.add_argument("--no-notify", action="store_true")

    report = sub.add_parser("report", help="Show recent metric count report")
    report.add_argument("--hours", type=int, default=24)

    validate = sub.add_parser(
        "validate-registry",
        help="Validate multi-store account registry JSON",
    )
    validate.add_argument(
        "--registry",
        default="",
        help="Path to stores registry JSON (default: GBM_STORE_REGISTRY)",
    )

    import_sheet = sub.add_parser(
        "import-account-sheet",
        help="Import client account sheet into a local profile directory",
    )
    import_sheet.add_argument("--xlsx", required=True, help="Path to the client xlsx file")
    import_sheet.add_argument(
        "--profile-dir",
        required=True,
        help="Local profile directory for generated stores_registry/login_inventory/checklist files",
    )

    next_verify = sub.add_parser(
        "next-verification",
        help="Show the next platform that should request a verification code",
    )
    next_verify.add_argument(
        "--profile-dir",
        required=True,
        help="Local profile directory generated by import-account-sheet",
    )
    next_verify.add_argument(
        "--message",
        action="store_true",
        help="Print a ready-to-send client message for the current verification step",
    )

    mark_verify = sub.add_parser(
        "mark-verification",
        help="Update verification status for one platform in the local profile",
    )
    mark_verify.add_argument("--profile-dir", required=True, help="Local profile directory")
    mark_verify.add_argument("--platform", required=True, help="Platform key, for example douyin")
    mark_verify.add_argument(
        "--status",
        required=True,
        choices=["pending", "ready", "completed", "skipped", "failed", "not_required"],
        help="New status",
    )

    profile_status = sub.add_parser(
        "profile-status",
        help="Show current execution status for one local client profile",
    )
    profile_status.add_argument("--profile-dir", required=True, help="Local profile directory")

    profile_board = sub.add_parser(
        "profile-board",
        help="Show the execution board for one local client profile",
    )
    profile_board.add_argument("--profile-dir", required=True, help="Local profile directory")

    profile_deliverable = sub.add_parser(
        "profile-deliverable",
        help="Render a customer-facing single-store delivery page",
    )
    profile_deliverable.add_argument("--profile-dir", required=True, help="Local profile directory")
    profile_deliverable.add_argument(
        "--output",
        default="",
        help="Optional output markdown path; if omitted, print to stdout",
    )

    profile_signal_deliverable = sub.add_parser(
        "profile-signal-deliverable",
        help="Render a customer-facing real-time sentiment delivery page",
    )
    profile_signal_deliverable.add_argument(
        "--profile-dir",
        required=True,
        help="Local profile directory",
    )
    profile_signal_deliverable.add_argument(
        "--output",
        default="",
        help="Optional output markdown path; if omitted, print to stdout",
    )

    profile_usage_guide = sub.add_parser(
        "profile-usage-guide",
        help="Render a customer-facing system usage guide",
    )
    profile_usage_guide.add_argument(
        "--profile-dir",
        required=True,
        help="Local profile directory",
    )
    profile_usage_guide.add_argument(
        "--output",
        default="",
        help="Optional output markdown path; if omitted, print to stdout",
    )

    latest_metrics = sub.add_parser(
        "latest-metrics",
        help="Show the latest stored metrics for one store",
    )
    latest_metrics.add_argument("--store-id", required=True, help="Store id")
    latest_metrics.add_argument("--platform", default="", help="Optional platform filter")

    score = sub.add_parser(
        "score-signals",
        help="Run store-level real-time sentiment matching against content input",
    )
    score.add_argument(
        "--input",
        required=True,
        help="Path to content items JSON",
    )
    score.add_argument(
        "--rules",
        default="",
        help="Path to signal rules JSON (default: GBM_SIGNAL_RULES)",
    )
    score.add_argument("--min-score", type=int, default=0)
    score.add_argument("--json", action="store_true")
    score.add_argument("--notify", action="store_true")
    score.add_argument(
        "--dedupe-hours",
        type=int,
        default=24,
        help="Suppress repeated push for the same store/content within N hours (default: 24)",
    )
    score.add_argument(
        "--allow-ambiguous",
        action="store_true",
        help="Do not suppress one piece of content matching multiple stores with close scores",
    )
    score.add_argument(
        "--mark-dispatched",
        action="store_true",
        help="Record current matched results into dispatch history even without webhook notify",
    )

    signal_board = sub.add_parser(
        "signal-board",
        help="Render a markdown watchboard for matched public sentiment content",
    )
    signal_board.add_argument("--input", required=True, help="Path to content items JSON")
    signal_board.add_argument(
        "--rules",
        default="",
        help="Path to signal rules JSON (default: GBM_SIGNAL_RULES)",
    )
    signal_board.add_argument("--min-score", type=int, default=0)
    signal_board.add_argument(
        "--output",
        default="",
        help="Optional output markdown path; if omitted, print to stdout",
    )

    profile_signals = sub.add_parser(
        "profile-signals",
        help="Run profile-level multi-platform real-time sentiment pipeline",
    )
    profile_signals.add_argument("--profile-dir", required=True, help="Local profile directory")
    profile_signals.add_argument("--mode", choices=["scheduled", "all"], default="scheduled")
    profile_signals.add_argument("--notify", action="store_true")
    profile_signals.add_argument("--mark-dispatched", action="store_true")
    profile_signals.add_argument("--dedupe-hours", type=int, default=24)
    profile_signals.add_argument("--min-score", type=int, default=0)
    profile_signals.add_argument("--attribution-window-hours", type=int, default=2)
    profile_signals.add_argument("--json", action="store_true")
    profile_signals.add_argument(
        "--report-output",
        default="",
        help="Optional output txt path for Feishu-ready signal report",
    )
    profile_signals.add_argument(
        "--board-output",
        default="",
        help="Optional output markdown path for signal watchboard",
    )

    return parser


def _print_summary(summary) -> None:  # noqa: ANN001
    print(f"run_id={summary.run_id}")
    print(f"mode={summary.mode}")
    print(f"metrics={summary.total_metrics}")
    print(f"stores={summary.total_stores}")
    if summary.collector_results:
        for item in summary.collector_results:
            print(
                f"collector={item.task_name} platform={item.platform} metrics={item.metric_count} stores={item.store_count}"
            )
    if summary.skipped_tasks:
        print("skipped=" + ",".join(summary.skipped_tasks))
    if summary.failed_tasks:
        print("failed=" + ",".join(summary.failed_tasks))


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    settings = Settings.from_env()
    configure_logging(settings.log_level)
    storage = Storage(settings.db_path)

    if args.command == "init-db":
        storage.init_schema()
        print(f"initialized db: {settings.db_path}")
        return 0

    if args.command == "run":
        active_platforms: set[str] | None = None
        allowed_store_ids: dict[str, set[str]] | None = None
        try:
            registry_entries = load_registry(settings.store_registry_path)
            binding_counts = enabled_platform_binding_counts(registry_entries)
            allowed_store_ids = enabled_store_ids_by_platform(registry_entries)
            active_platforms = {p for p, c in binding_counts.items() if c > 0}
            print(
                "registry_active_platforms="
                + ",".join(sorted(active_platforms))
            )
        except FileNotFoundError:
            # Registry is optional for MVP local smoke runs.
            active_platforms = None
            allowed_store_ids = None

        service = MonitorService(
            settings=settings,
            storage=storage,
            collectors=build_default_collectors(settings),
            notifier=FeishuNotifier(
                webhook=settings.feishu_webhook,
                at_mobiles=settings.feishu_at_mobiles,
            ),
            active_platforms=active_platforms,
            allowed_store_ids_by_platform=allowed_store_ids,
        )
        summary = service.run(
            mode=args.mode,
            dry_run=args.dry_run,
            notify=not args.no_notify,
        )
        _print_summary(summary)
        return 0

    if args.command == "report":
        rows = storage.summarize_recent(hours=args.hours)
        print(build_manual_report(datetime.now(settings.timezone), rows))
        return 0

    if args.command == "validate-registry":
        registry_path = settings.store_registry_path if not args.registry else Path(args.registry)
        entries = load_registry(path=registry_path)
        summary = summarize_registry(entries)
        print(f"registry={registry_path}")
        print(f"stores={summary['store_count']}")
        print(f"platform_bindings={summary['platform_bindings']}")
        print(f"api={summary['api_bindings']} cookie={summary['cookie_bindings']} manual={summary['manual_bindings']}")
        return 0

    if args.command == "import-account-sheet":
        outputs = import_account_sheet(
            xlsx_path=Path(args.xlsx),
            profile_dir=Path(args.profile_dir),
        )
        for key, value in outputs.items():
            print(f"{key}={value}")
        return 0

    if args.command == "next-verification":
        if args.message:
            print(build_client_verification_message(Path(args.profile_dir)))
            return 0
        step = next_verification_target(Path(args.profile_dir))
        if not step:
            print("next_verification=none")
            return 0
        print(f"platform={step['platform_key']}")
        print(f"platform_label={step['platform_label']}")
        print(f"priority={step['priority']}")
        print(f"login_method={step['login_method']}")
        print(f"second_factor={step['second_factor']}")
        print(f"store_link={step['store_link']}")
        return 0

    if args.command == "mark-verification":
        path = update_verification_status(
            profile_dir=Path(args.profile_dir),
            platform_key=args.platform,
            status=args.status,
        )
        print(f"updated={path}")
        return 0

    if args.command == "profile-status":
        print(build_profile_status(Path(args.profile_dir)))
        return 0

    if args.command == "profile-board":
        print(build_profile_execution_board(Path(args.profile_dir)))
        return 0

    if args.command == "profile-deliverable":
        deliverable = build_profile_deliverable(Path(args.profile_dir))
        if args.output:
            path = Path(args.output)
            path.write_text(deliverable + "\n", encoding="utf-8")
            print(f"written={path}")
            return 0
        print(deliverable)
        return 0

    if args.command == "profile-signal-deliverable":
        deliverable = build_profile_signal_deliverable(Path(args.profile_dir))
        if args.output:
            path = Path(args.output)
            path.write_text(deliverable + "\n", encoding="utf-8")
            print(f"written={path}")
            return 0
        print(deliverable)
        return 0

    if args.command == "profile-usage-guide":
        guide = build_profile_usage_guide(Path(args.profile_dir))
        if args.output:
            path = Path(args.output)
            path.write_text(guide + "\n", encoding="utf-8")
            print(f"written={path}")
            return 0
        print(guide)
        return 0

    if args.command == "latest-metrics":
        rows = storage.latest_store_metrics(
            store_id=args.store_id,
            platform=(args.platform.strip() or None),
        )
        if not rows:
            print("latest_metrics=none")
            return 0
        current_platform = None
        current_store_name = None
        for platform, metric_key, store_name, metric_value_num, metric_value_text, captured_at in rows:
            if current_store_name is None:
                current_store_name = store_name
                print(f"store={store_name}")
            if platform != current_platform:
                current_platform = platform
                print(f"[{platform}]")
            value = metric_value_text if metric_value_text not in {"", None} else metric_value_num
            print(f"- {metric_key}: {value} ({captured_at})")
        return 0

    if args.command == "score-signals":
        rules_path = settings.signal_rules_path if not args.rules else Path(args.rules)
        storage.init_schema()
        rules = load_signal_rules(rules_path)
        candidates = load_signal_candidates(Path(args.input))
        now = datetime.now(settings.timezone)
        matches = match_candidates(
            rules=rules,
            candidates=candidates,
            min_score_override=(args.min_score if args.min_score > 0 else None),
            allow_ambiguous=args.allow_ambiguous,
        )
        matches = storage.filter_new_signal_matches(
            matches=matches,
            now=now,
            dedupe_hours=max(args.dedupe_hours, 0),
        )
        if args.json:
            print(json.dumps(matches_to_json(matches), ensure_ascii=False, indent=2))
        else:
            report = build_signal_report(now, matches)
            print(report)
            delivered = False
            if args.notify:
                notifier = FeishuNotifier(
                    webhook=settings.feishu_webhook,
                    at_mobiles=settings.feishu_at_mobiles,
                )
                delivered = notifier.send_text(report) or not settings.feishu_webhook
            elif args.mark_dispatched:
                delivered = True

            if delivered:
                storage.record_signal_dispatches(dispatched_at=now, matches=matches)
        return 0

    if args.command == "signal-board":
        rules_path = settings.signal_rules_path if not args.rules else Path(args.rules)
        rules = load_signal_rules(rules_path)
        candidates = load_signal_candidates(Path(args.input))
        now = datetime.now(settings.timezone)
        matches, rejections = review_candidates(
            rules=rules,
            candidates=candidates,
            min_score_override=(args.min_score if args.min_score > 0 else None),
            allow_ambiguous=False,
        )
        board = build_signal_dashboard(now, matches, rejections)
        if args.output:
            path = Path(args.output)
            path.write_text(board + "\n", encoding="utf-8")
            print(f"written={path}")
            return 0
        print(board)
        return 0

    if args.command == "profile-signals":
        storage.init_schema()
        notifier = FeishuNotifier(
            webhook=settings.feishu_webhook,
            at_mobiles=settings.feishu_at_mobiles,
        )
        result = run_profile_signal_pipeline(
            profile_dir=Path(args.profile_dir),
            storage=storage,
            notifier=notifier,
            timezone=settings.timezone,
            mode=args.mode,
            notify=args.notify,
            mark_dispatched=args.mark_dispatched,
            dedupe_hours=args.dedupe_hours,
            min_score_override=(args.min_score if args.min_score > 0 else None),
            attribution_window_hours=args.attribution_window_hours,
        )
        if args.report_output:
            report_path = Path(args.report_output)
            report_path.write_text(result.report_text + "\n", encoding="utf-8")
            print(f"report_written={report_path}")
        if args.board_output:
            board_path = Path(args.board_output)
            board_path.write_text(result.board_text + "\n", encoding="utf-8")
            print(f"board_written={board_path}")
        if args.json:
            print(
                json.dumps(
                    {
                        "executed": result.executed,
                        "mode": result.mode,
                        "input_files": [str(path) for path in result.input_files],
                        "candidate_count": result.candidate_count,
                        "match_count": result.match_count,
                        "rejection_count": result.rejection_count,
                        "deduped_match_count": result.deduped_match_count,
                        "delivered": result.delivered,
                        "skipped_reason": result.skipped_reason,
                    },
                    ensure_ascii=False,
                    indent=2,
                )
            )
            return 0
        print(f"executed={result.executed}")
        print(f"mode={result.mode}")
        print(f"candidate_count={result.candidate_count}")
        print(f"match_count={result.match_count}")
        print(f"rejection_count={result.rejection_count}")
        print(f"deduped_match_count={result.deduped_match_count}")
        print(f"delivered={result.delivered}")
        if result.skipped_reason:
            print(f"skipped_reason={result.skipped_reason}")
        return 0

    parser.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
